### PR TITLE
Feature/oo adaptivity2

### PR DESCRIPTION
**Pull request by gardner48**
Update answers for LLNL/sundials#358

### CODE REVIEW

**Comment by balos1** [comment]
@gardner48 Since its conflicting, we may need to merge this manually and choose the changes in this branch.

**Comment by gardner48** [comment]
> @gardner48 Since its conflicting, we may need to merge this manually and choose the changes in this branch.

Just pushed the merge, I'll update the PR with the new commit and hopefully I've made all the correct selections

**Comment by balos1** [comment]
Appears to be good. I will merge this now and then the answers commit can be updated.

**Review by balos1 — APPROVED** [review]

**Comment by balos1** [comment]
Done, and oo-adaptivity2 commit updated.

**Pull request merged**
